### ISSUE TITLE
Refactor: decouple playstore url from Social component

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#100]
Make the application sharing dynamic, by providing a **shareApp** attribute in `config.json`.

`shareApp`: Object
+   playStoreUrl: String
+   message: String

**Comment by estefi-prieto** [comment]
I'm working on this

**Comment by estefi-prieto** [comment]
It was resolved in https://github.com/Cambalab/ns-vue-radio/pull/114
