### ISSUE TITLE
Refactor: add disable/enable functionality for firebase 

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#101]
We could enable/disable firebase by providing an attribute `useFirebae` in the `config.js`

~`useFirebase`: Boolean~

`State` and store index.js will have to be refactored ~and must use Firebase depending on the `useFirebase` value.~
Home.vue will have to be refactored too, when Firebase needs to be initialised.

+   [ ] Add google-services.json to .gitignore

**Comment by estefi-prieto** [comment]
If the application go to have Firebase installed, why it should be disable?

**Comment by sgobotta** [comment]
Well, that's a choice we have to make between this options:

+ We only support radio apps with firebase configuration 
+ We let developers choose not to use firebase (e.g.: they don't need push notifications)

**Comment by sgobotta** [comment]
It's decided that firebase will always be included in the applications deployment.

**Comment by estefi-prieto** [comment]
I'm working on this
