### ISSUE TITLE
Enhance Splash Screen configuration

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#102]
It would be nice to have the splash screen configured in some way that we don't have to dive into the Android folders to paste an image file.

**Comment by estefi-prieto** [comment]
`tns resources generate splashes <../image.png> --background <color>`

Generates all splashscreens for Android and iOS platforms and places the generated images in the correct directories under App_Resources/<platform> directory.

`--background` Sets the background color of the splashscreen. When no color is specified, a default value of white is used. <Color> is a valid color and can be represented with string, like white, black, blue, or with HEX representation.

**Comment by sgobotta** [comment]
Can you organise that information in a guide?

Please create a `tools` directory in the root of the project, and inside it create a README.md where you can formalise this intructions under the title: Assets, and subtitle: Generate splashscreen.

**Comment by estefi-prieto** [comment]
I'm working on this
