### ISSUE TITLE
Create ns-vue-radio tool: generate assets 

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#107]
This is a subtask of #105 

It's possible the script need images as inputs. In this issue we'll place documentation related to where these assets should be placed and instructions or link to instructions telling how to create a splash or app icons given media files

+   [x] Splash Screen input directory?
+   [x] App Icon input directory?

**Comment by estefi-prieto** [comment]
This is the [documentation to generate assets](https://github.com/Cambalab/ns-vue-radio/blob/develop/tools/assets.md) and have a guide to generate a splash screen and other to generate an app icon
I propose set the splash screen icon and the app icon in [ns-vue-radio/app/assets/images/](https://github.com/Cambalab/ns-vue-radio/tree/develop/app/assets/images)

**Comment by sgobotta** [comment]
What i meant in the checkboxes was to know where those assets will be placed. But since there's a script that automatically generates them, there's no need to clarify where we should set those assets.

I wouldn't set the assets that we'll generate in a source folder such as **app/...**, those images will not be part of the source code, in contrast, the generated ones will.

In this issue we can track the script development for assets generation. Therefore, let's continue writing the script so that it:

+   given an image directory:
     +  generates a splash screen
     +  generates the app icons
     +  generates the logo

In the directory, the script could try to find images with the following names:
+   splash.png
+   icon.png
+   logo.png

@EstefiCamba Do we know which image extensions are needed? (png, jpg,...)
