### ISSUE TITLE
Create ns-vue-radio tool: read from a keystore

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#110]
> At some point, the program will have to provide a keystore when building the application. We must define and document how this file is obtained/generated and where should it be placed before starting an application build.

Guide to keystore generation: https://github.com/Cambalab/ns-vue-radio/blob/develop/tools/guide-to-generate-a-keystore.md

This issue requires a keystore creation.

Given a `keystore path`, a `password`, an `alias`, and an `alias password` as arguments, the script searches for a keystore file and uses it during the tns build.

The build should continue normally until it ends.

Depends on #119

**Comment by estefi-prieto** [comment]
I'm working on this
