### ISSUE TITLE
Create ns-vue-radio tool: Fetch information from file

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#111]
Depends on #109 

Implement necessary code to ~fetch information from an API~ read data from a file, ~write it's content to a sample file with any name~. The script should read the information and declare an environment variable with a stringified json containing that data. Then, this data must be read from the webpack configuration and declared alongside with API_URL, when it should be JSON parsed. Finally, this variables are used in config.js to populate the attributes.

The script should continue until it succesfully finishes the build.

For this issue we'll need to create a dummy file to read, starting with this attributes:

**Json format**

### name

+   Details: The name of the radio
+   Type: `String`  

### social

+   Details: An object with social media information
+   Type: `Object`
+   Structure:
    +   facebookUrl: `String`
    +   instagramUrl: `String`
    +   twitterUrl: `String`

### colors

+   Details: An object with colors data
+   Type: `Object`
+   Structure:
    +   backgroundColor: `String: hex color`
    +   primaryText: `String: hex color`
    +   secondaryText: `String: hex color`

### bottomNavigationBar

+   Details: An object with data for the bottom navigation bar
+   Type: `Object`
+   Structure:
    +   activeColor: `String: hex color`
    +   inactiveColor: `String: hex color`
    +   backgroundColor: `String: hex color`

### streamingUrl

+   Details: the url to the live streaming
+   Type: `String`

**Comment by estefi-prieto** [comment]
I'm working on this

**Comment by sgobotta** [comment]
I saw the updates and reviewed some of the code.

I see the **name** prop is missing in the **config.js** file. Do you know what to do with it or should we clarify how to use the app name provided from the file?
