### ISSUE TITLE
Create a guide: how to generate a keystore

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#119]
We will need to generate keystores for as many applications we want to build. It would be extremely useful to have a guide that explains how to create one in a concise way.

I suggest the guide to be found in a directory /tools/keystore.md since it's part of the building script documentation.

**Comment by estefi-prieto** [comment]
Guide to [generate an upload key and keystore](https://developer.android.com/studio/publish/app-signing.html#generate-key)

**Comment by sgobotta** [comment]
> Guide to [generate an upload key and keystore](https://developer.android.com/studio/publish/app-signing.html#generate-key)

Is there a way to generate a keystore without downloading Android Studio? There must be a way using the android tools separately form the Andrid Sudio IDE.

**Comment by estefi-prieto** [comment]
I'm working on this

**Comment by estefi-prieto** [comment]
The keytool command-line utility can generate a keystore. To use keytool to generate a keystore for code signing, run the following command:

 `keytool -genkey -v -keystore <company’s-name.jks> -keyalg RSA -keysize 2048 -validity 10000 -alias <name-of-your-app>`

The keytool utility will ask you a number of questions, several of which are optional (name of organization, as well as the names of your city/state/country), but the most important ones are the passwords for both the keystore and the alias.

**Comment by sgobotta** [comment]
Looking good
