### ISSUE TITLE
Dynamically assign colors to the application layout

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#120]
The application layout is not ready to receive colors coming from a `config.js`.Changes have to be made to the NavigationBar and every place where the background color is being assign.
We need to add new properties to the `config.json` that will be used in the different layouts, we can add a value to them so that there's an assigned color by default:

### backgroundColor

+   **Type:** `String`

+   **Details:** a value that will be assigned to the background of every screen

+   **Default:** `#1a121f`

> This value will be used in the Home and any other component that requires background customization

### bottomNavigationBar

+   **Type:** `Object`

+   **Details:** an object containing the navigation bar appearance properties

+   **Example:** object with default values

```
bottomNavigationBar: {
  activeColor: '#E500A2',
  inactiveColor: '#808080',
  backgroundColor: '#1a121f'
}
```

> This styles will be applied to the BottomNavigationBar in the Home component. Note that keyLineColor can be removed, it's not used at all.

### primaryText

+   **Type:** `String`

+   **Details:** The primary text color of the whole application. It's currently being assigned using scss in a `class` property. We'll have to find a way to assign values from the `config.js` to the `class` property.

+   **Default:** `#E500A2`

### secondaryText

+   **Type:** `String`

+   **Details:** The primary text color of the whole application. It's currently being assigned using scss in a `class` property. We'll have to find a way to assign values from the `config.js` to the `class` property.

+   **Default:** `#ffffff`

**Comment by estefi-prieto** [comment]
I'm working on this

**Comment by estefi-prieto** [comment]
I propose the changes shown below, to use the fields as css clases and define the fields in a colors field in the config.js
 
#### backgroundColor
* Type: `Object`
```
'backgroundColor': {
  backgroundColor: '#432f4f'
}
```

#### panelBackgroundColor
* Type: `Object`
```
'panelBackgroundColor': {
  backgroundColor: '#1a121f'
}
```

#### primaryText
* Type: `Object`
```
'primaryText': {
  color: '#E500A2'
}
```

#### secondaryText
* Type: `Object`
```
'secondaryText': {
  color: 'ffffff'
}
```

**Comment by sgobotta** [comment]
Looks nice to me, good to go! We're going to use them to a style property in vue components
