### ISSUE TITLE
Configure manifest with a proper app name

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#136]
The config file will provide a **name** prop, which must be the same as the one in `google-services.json`. This prop will be our input to edit the manifest, so that the Android app will be registered with that name.

So, somehow we need to change the android manifest or the `package.json` in the `nativescript.id` prop to use that name. Is there any other value that must be changed from this manifest?

For example: `org.{name}.radio`

Later on we can get a proper value for the domain to use custom ones from the backend (org, com, coop, etc...). It can be org for now.

**Comment by estefi-prieto** [comment]
I'm working on this

**Comment by sgobotta** [comment]
This was closed in #137
