### ISSUE TITLE
Application Id Configuration

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#138]
It would be great to generalise even more the android and firebase configuration of the application. This can be achieved by changing the name of the application and the application package name to a more generic alternative, (e.g.: Radio as name, coop.radio.app as package). We'll have to create a new google-services file and update the gradle, package.json and android manifest as necessary.

**Comment by sgobotta** [comment]
Note to myself for documentation: this solution only works for google-services.json files with `org.myAppName.radio` as id. Currently we can't use other domains than `org` and `radio` for our apps.

I'll be running those tests.

**Comment by NataliaSuarez** [comment]
I've generated a new keystore for create a new google-services.json with ```coop.radio.app``` and i've changed app.grandle and package.json. Do i need change ```org.camba.radio``` for ```coop.radio.app``` in script too?
