### ISSUE TITLE
Create an ns-vue-radio-tool: generate Icon

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#144]
**Is your feature request related to a problem? Please describe.**
We could stop using the vue nativescript default icon to some sort of image of the user's like.

**Describe the solution you'd like**
Should we use the `logo.png` to create icons or provide a customised one?

I can't quite remember what we talked but, do we have this already solved with the assets generation script?

**Comment by sgobotta** [comment]
Check that the application icon in the application box is the one provided as `logo.png`.

**Comment by NataliaSuarez** [comment]
The `logo.png` provided in assets folder to script is the same in application box, after create the app this file is saved in project.

**Comment by sgobotta** [comment]
Nice, the icon is being rendered properly. Closing this
