### ISSUE TITLE
Create Tool: The Splash scren is not being generated

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#148]
**Is your feature request related to a problem? Please describe.**
The splashscreen is not being generated when the script executes: `tns resources generate splashes <assetPath>`

**Comment by estefi-prieto** [comment]
I'm working on this

**Comment by estefi-prieto** [comment]
When I try:  
`tns resources generate splashes <assetPath> --log trace`  
thows the bellow error:  
```
Error: Trying to handle SIGINT event. CLI overrides this behavior and does not allow handling SIGINT as this causes issues with Ctrl + C in terminal
```
