### ISSUE TITLE
Create a new logo

### ISSUE THREAD

**Issue by solardata** [Cambalab/ns-vue-radio#15]
**Is your feature request related to a problem? Please describe.**
The ns vue radio doesn't have any logo to help visualizations

**Describe the solution you'd like**
This will need a logo idea in png and svg format, 520 x 520px and 128 x 128 px

**Describe alternatives you've considered**
Maybe we could create a version inspired to radio icons and native vue js logo.

**Comment by FacundoMainere** [comment]
solved by #16
