### ISSUE TITLE
Configure endpoint URLs

### ISSUE THREAD

**Issue by FacundoMainere** [Cambalab/ns-vue-radio#150]
**Is your feature request related to a problem? Please describe.**
not all servers have the same endpoint naming convention

**Describe the solution you'd like**
We need the API endpoint to be able to have custom URLS

**Describe alternatives you've considered**
Use config file `app/config.js` to setup this urls and use them in `app/api/ShowService.js` and `app/api/PodcastService.js`

for example:
```
{
shows: "/api/programs",
podcasts: "/api/podcasts",
currentShow: "/api/programs/current"
}
```

**Comment by estefi-prieto** [comment]
I'm working on this

**Comment by estefi-prieto** [comment]
I think that the urls should come from [config file](#111) and in the config.json file should have default values

**Comment by sgobotta** [comment]
I'm not sure about this. What's blocking us from using the same endpoints for every service? I mean, if the services are implemented in the server, what would be a good reason to let a user decide how the endpoint is named?

If we need to do that we should consider which params we want the user to customize. What would be a good example of a custom url? Or, how are we planning to write them in a config.js?

Maybe a user could customise the amount of podcast to retrieve, for example. Any other ideas?

**Comment by estefi-prieto** [comment]
> What would be a good example of a custom url? Or, how are we planning to write them in a config.js?

I propose use the the url below as default:
- currentShowEndpoint: '/api/programs/current'
- showsEndpoint: '/api/programs'
- podcastsEndpoint: '/api/podcasts'

**Comment by sgobotta** [comment]
Okay, it looks good to me. Though I'd refactor `api` as an url prefix variable.
