### ISSUE TITLE
Update readme with logo and sponsorship

### ISSUE THREAD

**Issue by solardata** [Cambalab/ns-vue-radio#18]
Now the readme doesn't has the logo of the ns vue radio and Cambá.

Add some style and the logos at the readme description

Tutorials and info to make great readme text

https://jesuslc.com/2016/07/12/como-escribir-un-readme-que-mole/

https://dotdev.co/how-to-write-a-readme-that-rocks-bc29f279611a

**Comment by FacundoMainere** [comment]
done!
