### ISSUE TITLE
Move hardcoded social network options to config file

### ISSUE THREAD

**Issue by FacundoMainere** [Cambalab/ns-vue-radio#6]
Right now social networks are hardcoded in [this file](https://github.com/Cambalab/ns-vue-radio/blob/develop/app/components/Redes.vue).
The idea is to move them to a [config file](https://github.com/Cambalab/ns-vue-radio/blob/develop/app/config.js) where you can select which ones do you want.

**Comment by estefi-prieto** [comment]
I'm working on this.

**Comment by FacundoMainere** [comment]
done!
