### ISSUE TITLE
Upgrade application to nativescript 6

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#66]
In order to work with the latests nativescript updates we should consider to migrate the application to the latest nativescript cli.

Steps below:

Make sure we're working with the latest tns
```bash
npm install --global nativescript@latest
```
Migrate application
```bash
tns migrate
```
*This will generate a backup directory with the assets and create the new directory for the current assets.*

Update webpack configuration
```bash
./node_modules/.bin/update-ns-webpack --configs
```
*It is possible that changes in production/development mode have to be made, since we manually configured it in the past to read values from API_URL*

Check that everything is working fine
```bash
tns debug android --bundle --compileSdk 28
```

Some [build scripts](https://gist.github.com/sgobotta/bcab62fdf8a36f99f722733221695aed) that could help

**Comment by estefi-prieto** [comment]
I'm working on this
