### ISSUE TITLE
Update main.js

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#68]
For a proper migration, we'll have to apply a few updates in the main.js

+   [x] Update [nativescript-bottom-navigation](https://npmjs.com/package/nativescript-bottom-navigation) to "^1.5.1"
+   [x] Rename `BottomNavigation` to `BottomNavigationBar` (this will have to be updated in the Home.vue component too
+   [ ] Update vue-dev-tools usage (a host option is required now, keep it commented anyway)

**Comment by estefi-prieto** [comment]
I'm work on this

**Comment by sgobotta** [comment]
VueDevtools needs to be installed properly. Steps below:

+   [x] install vue-devtools dependencies
```
npm install --save nativescript-toasty nativescript-socketio
```
+   [x] Modify main.js so VueDevtools is instanced like:
```
Vue.use(VueDevtools, { host: 'your-lan-ip' })
```
+   [x] Replace `Vue.config.silent = true` for `Vue.config.silent = (TNS_ENV === 'production')`
+   [x] Remove breaklines between imports
+   [x] Add debugging instructions to README.md just pointing to this [link](https://nativescript-vue.org/en/docs/getting-started/vue-devtools/)
+   [x] Add TNS_ENV to .eslintrc `"TNS_ENV": true`
