### ISSUE TITLE
Home: translate comments to English (if necessary)

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#78]
The Home component still has documented code in Spanish. It would be nice to translate them to English, or remove them if they're trivial.

+   [x] Suggest translations in this issue
+   [ ] Open PR

**Comment by estefi-prieto** [comment]
I'm working on this

**Comment by estefi-prieto** [comment]
My suggest translation is: *when the app is foreground and recived a message gets the message data.topic screen* and I propose move the comment to top of `if`

**Comment by sgobotta** [comment]
Suggested text: when the app is in the foreground and receives a message, the corresponding data.topic tab is shown

**Comment by estefi-prieto** [comment]
Great! I like it.
