### ISSUE TITLE
Store: refactor literals to string constants

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#83]
Mutations and components constantly calls mutations from the store. We're currently defining them with a literal string. It would be nice to define a constants file in the store directory so that every definition depends on a unique string defined in a single file.

This proposal attempts to provide a little bit of flexibility if we ever have to rename a mutation.

This issue includes a refactor mainly in the mutations file as well as every piece of code that calls mutations using a literal string.

**Comment by estefi-prieto** [comment]
I'm working on this

**Comment by estefi-prieto** [comment]
It was resolved in https://github.com/Cambalab/ns-vue-radio/pull/87
