### ISSUE TITLE
Define different environment configuration files

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#92]
Currently we have a single environment json file that defines the backend env variables.
We could separate those urls into different files where we can easily distinguish between development and production environments.

My proposal is to deprecate backend.json and define two new files in the same directory:
+   development.json
+   production.json

Example:

```json
{
  "API_URL": "my-api-url"
}
```

Then we will have to slightly modify the webpack config so that we don't require a single environment json file but choose between two different environments. We can use **require** from an interpolated string from ./environments/{production|development}. Example
```js
const environment = require(`./environments/${mode}`);
``` 

The last technical step is to apply these changes where global variables are defined (line 243). We will have to replace api_url to the new one coming from the {development|production}.json file

After all changes are made and the application runs properly with he new configurations we'll need to add the environments directory to .gitignore and write documentation explaining how to properly setup the app with this files, because webpack will always try to look for an API_URL variable.

Depends on: #91

**Comment by estefi-prieto** [comment]
It was resolved in https://github.com/Cambalab/ns-vue-radio/pull/95
