### ISSUE TITLE
Eslint is not working

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#94]
Eslint is currently throwing this error in a text editor:

`Error while running ESLint: Environment key "TNS_ENV is unkwown`

We need to move the TNS_ENV prop from **env** to **globals** in the .eslintrc file.

**Comment by estefi-prieto** [comment]
I'm working on this

**Comment by estefi-prieto** [comment]
It was resolved in https://github.com/Cambalab/ns-vue-radio/pull/96
