### ISSUE TITLE
Refactor: decouple email from WriteUs component

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/ns-vue-radio#97]
Make the email dynamic by proving a `writeEmailTo` prop in `config.js` with a desired email as value.

**Comment by estefi-prieto** [comment]
We have support to send emails to different accounts. I think that `writeEmailTo` prop should be `List`

**Comment by sgobotta** [comment]
Ok, it is an array of string then.

**Comment by estefi-prieto** [comment]
I'm working on this

**Comment by estefi-prieto** [comment]
It was resolved in https://github.com/Cambalab/ns-vue-radio/pull/116
